apiVersion: v1
kind: Service
metadata:
  name: hero-manager-backend
  labels:
    name: hero-manager-backend
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: hero-manager-backend
